spring.datasource.url=jdbc:h2:file:./data/meubanco
#diz onde achar o meu banco, senao tiver vai criar esse arquivo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
# por padrão ele vai usar o usuario "sa"
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# agora ele vai usar comando "H2Dialect" por baixo dos panos;

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# configurnado o jpa pro h2  e formato sql, padrão do h2

spring.h2.console.enabled=true
#ativo o terminal do h2
spring.h2.console.path=/h2-console
# acessando em http://localhost:8080/h2-console